version: "2017-09-20"
pipeline:
- id: build
  type: script
  commands:
  - desc: Build and push Docker image
    cmd: |
      if [[ $CDP_TARGET_BRANCH == master && ! $CDP_PULL_REQUEST_NUMBER ]]; then
        RELEASE_VERSION=$(git describe --tags --always --dirty)
        IMAGE=registry-write.opensource.zalan.do/teapot/external-dns:${RELEASE_VERSION}
      else
        IMAGE=registry-write.opensource.zalan.do/teapot/external-dns-test:${CDP_BUILD_VERSION}
      fi
      docker build --squash --tag "$IMAGE" .
      docker push "$IMAGE"
