# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

required = ["github.com/kubernetes/repo-infra/verify/boilerplate/test"]
ignored = ["github.com/kubernetes/repo-infra/kazel"]

[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "~10.0.4-beta"

[[constraint]]
  name = "github.com/Azure/go-autorest"
  version = "~10.9.0"

[[constraint]]
  name = "github.com/alecthomas/kingpin"
  version = "~2.2.4"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "~1.13.7"

[[constraint]]
  name = "github.com/cloudflare/cloudflare-go"
  version = "0.7.3"

[[constraint]]
  name = "github.com/digitalocean/godo"
  version = "~1.1.0"

[[constraint]]
  name = "github.com/dnsimple/dnsimple-go"
  version = "0.14.0"

[[constraint]]
  branch = "master"
  name = "github.com/infobloxopen/infoblox-go-client"

[[constraint]]
  name = "github.com/linki/instrumented_http"
  version = "0.2.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.0-pre1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "~1.0.3"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "~1.2.1"

[[override]]
  name = "github.com/kubernetes/repo-infra"
  branch = "master"

[[constraint]]
  name = "github.com/nesv/go-dynect"
  version = "0.6.0"

[[constraint]]
  name = "github.com/exoscale/egoscale"
  version = "~0.11.0"

[[constraint]]
  name = "github.com/oracle/oci-go-sdk"
  version = "1.8.0"

[[constraint]]
  name = "github.com/linode/linodego"
  version = "0.3.0"

[[constraint]]
  name = "github.com/aliyun/alibaba-cloud-sdk-go"
  version = "1.27.7"

[[constraint]]
  name = "istio.io/istio"
  version = "1.0.0"

[[override]]
  name = "github.com/golang/glog"
  source = "github.com/kubermatic/glog-logrus"

[[override]]
  name = "github.com/golang/protobuf"
  version = "1.1.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "8.0.0"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.0"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.0"

[[override]]
  name = "golang.org/x/sys"
  revision = "13d03a9a82fba647c21a0ef8fba44a795d0f0835"

[[override]]
  name = "github.com/spf13/pflag"
  version = "1.0.2"

[[override]]
  name = "golang.org/x/net"
  revision = "161cd47e91fd58ac17490ef4d742dc98bb4cf60e"

[[constraint]]
  name = "github.com/miekg/dns"
  version = "1.0.8"

[[constraint]]
  name = "github.com/sanyu/dynectsoap"
  branch = "master"
